### ISSUE TITLE
Verbesserungen für Dice

### ISSUE THREAD

**Issue by lukasrad02** [SaturnHafen/hpi-sk-web#1]
Das Beispiel gefällt mir an sich schon sehr gut, gerade die Idee, dass die Würfehzahl festgelegt werden kann, um noch ein bisschen mehr Interaktivität zu schaffen, finde ich schön.

Folgende Aspekte sind mir noch aufgefallen, die verbessert werden könnten, damit die Teilnehmenden den Code auch nachvollziehen können:

- Einrückung in https://github.com/SaturnHafen/hpi-sk-web/blob/main/Dice/script.js vereinheitlichen (meist 4er-Tabs, manchmal 2 Spaces)
- Normale `for`-Schleife statt `forEach`-Methode (https://github.com/SaturnHafen/hpi-sk-web/blob/main/Dice/script.js#L24), `forEach` wird nicht vorgestellt
- Es wäre schön, wenn auch die Summe der Würfel in einer kleinen Schleife berechnet und in der Textbox mit ausgegeben werden könnte
- Vllt könnten statt der SVGs Rastergrafiken verwendet werden, da viele wahrscheinlich SVGs gar nicht kennen
- `value` gibt auch für Input-Elemente vom typ `number`einen String zurück. Auch wenn es eigentlich durch die Eingabevalidierung im Browser nicht zu Problemen kommen sollte, wäre es trotzdem gut, den Wert noch mal in einen Integer zu casten
- Wir verwenden in der JS-Einführung `"` statt `'` (ist aber nur eine Kleinigkeit und dürfte mit Syntax-Highlighting den meisten wahrscheinlich gar nicht auffallen, dass es zwei verschiedene Zeichen sind)

**Comment by SaturnHafen** [comment]
Ich hab jetzt einfach mal die SVGs der Vollständigkeit halber dagelassen.
