### ISSUE TITLE
Verbesserungen für Timer

### ISSUE THREAD

**Issue by lukasrad02** [SaturnHafen/hpi-sk-web#3]
Die Animation der Progressbar :heart_eyes:

Aber um ernst zu bleiben :joy: Sehr schönes Projekt, aber auch mit entsprechend viel und komplexem Code und insbesondere auch umfangreichem CSS-Teil. Für fortgeschrittenere Gruppen sicherlich schön, um sich in dem Bereich ein wenig inspirieren zu lassen, wir sollten nur, wenn wir die Projekte vorstellen, dazu sagen, dass das auf keinen Fall das Niveau ist, was wir erwarten!

**Comment by SaturnHafen** [comment]
Ist tatsächlich etwas, was ich vorher schonmal für ne andere Veranstaltung gebaut hatte, deswegen auch mit animation, farbänderung, `::before`, ...
